export type AppErrorCode =
  | 'UNKNOWN_ERROR'
  | 'NETWORK_UNAVAILABLE'
  | 'STORAGE_UNAVAILABLE'
  | 'STORAGE_SECURITY_ERROR'
  | 'STORAGE_QUOTA_EXCEEDED'
  | 'STORAGE_DATA_CORRUPTED'
  | 'STORAGE_SCHEMA_INVALID'
  | 'STATE_VERSION_MISMATCH'
  | 'INVALID_FORM_INPUT'
  | 'INSUFFICIENT_BALANCE'
  | 'INSUFFICIENT_USD_BALANCE'
  | 'INSUFFICIENT_QUOTE_BALANCE'
  | 'INSUFFICIENT_BASE_BALANCE'
  | 'RESERVED_BALANCE_INSUFFICIENT'
  | 'INVALID_ORDER'
  | 'INVALID_AMOUNT'
  | 'INVALID_PRICE'
  | 'REQUIRED_FIELD'
  | 'INVALID_NUMBER'
  | 'NEGATIVE_VALUE'
  | 'POSITIVE_VALUE_REQUIRED'
  | 'ZERO_VALUE'
  | 'TOO_MANY_DECIMALS'
  | 'VALUE_TOO_SMALL'
  | 'VALUE_TOO_LARGE'
  | 'ORDER_NOTIONAL_TOO_LOW'
  | 'ORDER_NOTIONAL_TOO_HIGH'
  | 'DUPLICATE_SUBMISSION'
  | 'DUPLICATE_ALERT'
  | 'INVALID_ALERT_TARGET'
  | 'MARKET_UNAVAILABLE'
  | 'ASSET_UNAVAILABLE'
  | 'ASSET_NOT_FOUND'
  | 'PAIR_NOT_FOUND'
  | 'ROUTE_NOT_FOUND'
  | 'EXPORT_FAILED'
  | 'EXPORT_NO_DATA'
  | 'CSV_DOWNLOAD_BLOCKED'
  | 'ADDRESS_COPY_FAILED'
  | 'INVALID_WITHDRAWAL_ADDRESS'
  | 'WITHDRAWAL_FEE_EXCEEDS_BALANCE'
  | 'SUPPORT_TICKET_CREATE_FAILED'
  | 'BUILD_ERROR';

export { createAppError, ERROR_CATALOG } from './error-messages';

export interface AppError {
  code: AppErrorCode;
  title: string;
  message: string;
  recoverable: boolean;
  actionLabel?: string;
  action?: 'retry' | 'reset_demo_data' | 'go_home' | 'dismiss';
  details?: Record<string, unknown>;
}
